//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooFlyerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer
    {
        public int Id { get; set; }
        public int User { get; set; }
        public int OpeningHours { get; set; }
        public int Price { get; set; }
        public int Address { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual OpeningHour OpeningHour { get; set; }
        public virtual Price Price1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
