//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooFlyerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpeningHour()
        {
            this.Flyers = new HashSet<Flyer>();
        }
    
        public int Id { get; set; }
        public int Season { get; set; }
        public int Day { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Day Day1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flyer> Flyers { get; set; }
        public virtual Season Season1 { get; set; }
    }
}
